"""alter timestamp in post table from 

Revision ID: 2b066a0e2c42
Revises: da7c837c7e66
Create Date: 2023-02-05 15:05:31.335245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b066a0e2c42'
down_revision = 'da7c837c7e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
