"""auto_generate from models file

Revision ID: da7c837c7e66
Revises: a8bf528da88c
Create Date: 2023-02-05 13:33:39.749119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da7c837c7e66'
down_revision = 'a8bf528da88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_id', 'user_id')
                    )
    op.alter_column('posts', 'published',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=text('now()'))
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=text('now()'))
    op.alter_column('posts', 'published',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=text('true'))
    op.drop_table('votes')
    # ### end Alembic commands ###
